### ISSUE TITLE
Issues with 4k inputs and some image artifacts

### ISSUE THREAD

**Issue by torsteingrindvik** [hasenbanck/block_compression#6]
Hi, cool project. I was just looking into whether BC6H compression was possible in real time so I ended up here.

I tried running the compression binary. If I give it a 4k input it crashes:

```
Caused by:
  In Device::create_texture, label = '/path/to/4k.png'
    Dimension X value 3840 exceeds the limit of 2048
```

That's a minor issue, I suppose the device has to be asked to support larger limits or something.

I gave it a 1080p image instead (of a Blender splash screen: https://cloud.blender.org/p/gallery/5dd6d7044441651fa3decb56).

On my laptop mobile 4080 I get around

- 220ms to compress 1080p, very slow preset
- 0.8ms to compress 1080p, very fast preset

I'm not sure if it's possible to extrapolate but perhaps around 4ms for 4k then if the very fast preset is acceptable. Not too bad!

However there are some artifacts:

![Image](https://github.com/user-attachments/assets/6c452fce-11dd-4981-95bc-c7275ee6c762)

Source image at the bottom. Slow middle, fast on top.
They have these strange green pixels, and the overall brightness seems too low.

I'm comparing each image region in this program: https://gitlab.gnome.org/YaLTeR/identity

In order to decompress the compressed image I'm using an nvidia tool `nvdecompress` via https://developer.nvidia.com/gpu-accelerated-texture-compression.

If I compress and decompress using the NVIDIA tool I get a more expected result:

![Image](https://github.com/user-attachments/assets/aa2cb3aa-130f-490b-b82e-43c56f933c84)

Of course it's hard to tell if it's the compression, the DDS format, or something else that's gone wrong.

**Comment by hasenbanck** [comment]
Since you talked about a lot, I will try to clear your issues:

1. The compressor programm is currently more of an "this is how you use this library" program and in it's current form not intended to be a user facing program with all the bells and whistles. The crash you experiences is simply the limit that is currently set to the standard default for downleveled backends. You can increase the limit on your side. I'm open to the idea to make the compressor a user facing CLI client, but currently I don't have time to implement such a proper CLI ([Link](https://github.com/hasenbanck/block_compression/blob/ac6c395826216539fc25c79cfa57b52cb9f19d23/compressor/src/main.rs#L100)).

2. Are you using proper HDR encoded images when using BC6H? If you are, then it's no wonder why you experience issues with the CLI and gamme correction: The CLI currently handles all input as LDR images and will crush your HDR image data ([Link](https://github.com/hasenbanck/block_compression/blob/ac6c395826216539fc25c79cfa57b52cb9f19d23/compressor/src/main.rs#L132)).

3. I'm not sure what kind of artifacts you are seeing, since the green pixels seem to be inserted by the identity program? Are you also seeing them when you open it with renderdoc like that?

**Comment by torsteingrindvik** [comment]
Yep apologies for stacking multiple issues into one.

Will reply back in same order:

1. That sounds reasonable
2. No, as far as I am aware the Blender image is LDR
3. If I open the images in my default OS image viewer I still get the green pixels. I'm not sure how to capture the compressor in RenderDoc since it's not a graphical app

Also feel free to close this issue if it doesn't help you, I just wanted to bring awareness to these things if you were not already.

**Comment by hasenbanck** [comment]
Can you please provide the source image you are trying to compress? I would like to try to reproduce the issue.
Is there any reason for using BC6H? BC7 should give better results for LDR sRGB image.
You can open DDS files with renderdoc, and it's know to render DDS files well.

**Comment by torsteingrindvik** [comment]
![Image](https://github.com/user-attachments/assets/a8e214d4-1adf-41c5-b6b8-76a029c416e8)

This is the image I used.

> Is there any reason for using BC6H?

Yes, I am working on a video pipeline (not rendered) so I don't have an alpha channel.
Today it's mostly f16 per channel, and it supports HDR.

So BC6H seems like a really good fit.

But from what I can tell from what I've found 4k input BC6H encoding is likely too expensive even on high end consumer GPUs.
Too expensive meaning that it would likely eat to much out of e.g. a 16ms frame budget.

**Comment by hasenbanck** [comment]
Thanks for the image. I will try to replicate the issue on my side.

I made a small change to the compressor CLI to use the maximum supported limits of the adapter. So you should be able to test 4K images now.

Doing BC6H compression realtime is indeed not really a good option. We use online compression on level load of an open source port of legacy game client.

I don't think there is a good use case for BC compression on the GPU for realtime data, since you need to upload the uncompressed image anyhow to the VRAM.

**Comment by torsteingrindvik** [comment]
> Doing BC6H compression realtime is indeed not really a good option

This is what I feared! Good to have it confirmed though, thank you.

> I don't think there is a good use case for BC compression on the GPU for realtime data, since you need to upload the uncompressed image anyhow to the VRAM.

For my use case there are a lot of CUDA kernels (if BC compression would work I might have ported some of it from WGPU to CUDA) reading image data per frame. On the order of 100s per frame.

So the reason I was looking at BC6H was to see if the cost of compression at the start of frame to reduce the memory footprint might be worth it since texture reads for all subsequent kernels in the frame should be somewhat cheaper.

Now I know that BC6H isn't a great candidate for that.

If you know of any cheap schemes to reduce bits per pixel access on textures (either LDR or HDR) with cheap encoder/decoder support I'd be happy to take pointers.

**Comment by hasenbanck** [comment]
I was able to reproduce the issue on my side. Oddly enough this issue was not visible with the existing textures I used for testing. I will include the image in the test suite and will try to hund down the bug in BC6H.

If you can live with half the resolution in chroma, you could use a YUV420P encoding. A texture format that provides that is NV12.

**Comment by torsteingrindvik** [comment]
Can confirm 4k inputs now work with the example.

> you could use a YUV420P encoding

Worth considering, thanks for mentioning that.


I'm also considering compression on grayscale inputs.
I can happily report that my mobile 4080 reports "Compression took: 0.115 ms" for BC4 on the Blender image at 4k.
I can't see any obvious artifacts after decompressing either.
Great job 👍

**Comment by hasenbanck** [comment]
@torsteingrindvik Could you please test the newest commit? I think I fixed the issue with the artifacts. I noticed that all pixels that were affacted where black and it turned out, that I have to handle "0.0" values specially when interpreting it's bit pattern.

I would like to close this issue if the artifacts are gone on your end!

**Comment by torsteingrindvik** [comment]
![Image](https://github.com/user-attachments/assets/de792eb3-a473-419d-bc89-1819e9a26c2c)

Here's a cropped comparison of the original at the top vs. the compressor on main encoding using BC6H then decompressed via `nvdecompress`.

The results are much better. I still see a stray very green pixel, and the overall output image is still much darker.

**Comment by hasenbanck** [comment]
I don't know what `nvdecompress` does, but BC6H stores the color as f16 values, so having them in linear space makes the most sense. So when you are decoding the DDS, you need to convert the linear color into sRGB space! When you use RenderDoc, you can actually apply sRGB gamma correction and the image will be interpreted correctly. We could include a CLI flag to change this behavior, but this is out of scope of this issue.

Please also don't compare the output of nvdecompress's BC6H with the output of the Intel's ISPC BC6H version, which this crate ported to WGSL. I compared the output of the WGSL shader with the output of the `intel_tex_2` crate and the PSNR values are extremly close.

I will close this issue for now, since having quality parity against other BC6H encoders is currently not a goal of this crate and does not hint at a bug (BC are lossy codecs, so artifacts are to be expected).

Please feel free if you find a deviation in quality when compared against the [intel_tex_2](https://github.com/Traverse-Research/intel-tex-rs-2) crate or the ISPCTextureCompressor[](https://github.com/GameTechDev/ISPCTextureCompressor)
